### ISSUE TITLE
Package ID warnings and error(s) querying package graph on most-recent nightly runs

### ISSUE THREAD

**Issue by zeeshanlakhani** [nextest-rs/nextest#1232] opened 2024-01-18 11:50 UTC
Firstly, just wanted to give a ❤️ and thank you for this project! 

Note: This started with the latest version of Rust nightly. 

```
nightly-x86_64-apple-darwin unchanged - rustc 1.77.0-nightly (6ae4cfbbb 2024-01-17)
```

It does not happen on stable. 

After compilation, we get a series of dependency-related warnings like *package ID `names 0.14.0 (registry+[https://github.com/rust-lang/crates.io-index)`](https://github.com/rust-lang/crates.io-index))* which wasn't produced by cargo metadata. Then, as one example, it errors out with:

```
error: failed to parse messages generated by Cargo

Caused by:
  error querying package graph

Caused by:
  unknown package ID: homestar-functions-add 0.1.0 (path+file:///home/runner/work/homestar/homestar/homestar-functions/add)
```

This also occurs for me locally with the latest nightly release. 

Link to CI Github Action(s): https://github.com/ipvm-wg/homestar/actions/runs/7569332335/job/20612405047?pr=506#step:10:1505

**Comment by Tom-Goring** [comment] 2024-01-18 13:50
Getting the same thing on internal CI + local builds on 1.77.0-nightly (6ae4cfbbb 2024-01-17). 

I did get a working build yesterday on 1.77.0-nightly (098d4fd74 2024-01-16) so presumably it's today's nightly that caused this?

**Comment by zeeshanlakhani** [comment] 2024-01-18 13:51
@Tom-Goring yep, seems to be the most recent 01-17 nightly.

**Comment by lvyitian** [comment] 2024-01-18 15:06
This might be caused by:https://github.com/rust-lang/cargo/pull/12914
And it should be fixed by:https://github.com/rust-lang/cargo/pull/13311

**Comment by sunshowers** [comment] 2024-01-18 16:49
Yes, I believe @lvyitian is correct. We treat package IDs as opaque generally so the format change itself isn't a problem. However, we match up the package IDs from cargo metadata with the ones from JSON messages.

**Closed** 2024-01-20 02:29 UTC
